### ISSUE TITLE
Signin endpoint

### ISSUE THREAD

**Issue by itsjasonlee** [DavisCSClub/daviscsclub.org#14]
Please add the link: 
https://docs.google.com/forms/d/e/1FAIpQLScSJeK0j7jOOs8eJya0sD9fy3uUFsZdp5bDoh-DF5vITlEogQ/viewform

**Comment by itsjasonlee** [comment]
If possible, can we use the same code to create a sign in endpoint for the bit byte link?

https://docs.google.com/forms/d/e/1FAIpQLSc4hD717bmx3zf10oDAzJCgQ1U1Wb-Cz6WlOzUHpFZlQhIA7Q/viewform

**Comment by bryngo** [comment]
Sign in endpoint has been completed via issue #13 . To add the bitbtye endpoint, feel free to make a new branch (branch #14) or continue working on the same one. I will leave this up to you.
